In [9]:
import numpy as np

In [12]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a.ndim #check dimension

1

In [16]:
b = np.array([[1,2,3,4],[6,7,8,9]])
b

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [18]:
b.ndim #2 dimension array

2

In [21]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #3 dimension array
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
c.ndim

3

## 0's and 1'



In [26]:
var = np.zeros(10)

In [27]:
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
var=np.ones(5)
var

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [32]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## functions

In [38]:
var = np.array([22,566,44,78])
var

array([ 22, 566,  44,  78])

In [39]:
type(var)

numpy.ndarray

In [40]:
var.argmax() # max value in index position

1

In [41]:
var.argmin()

0

In [42]:
var[0]

22

In [43]:
var[1]

566

In [44]:
var

array([ 22, 566,  44,  78])

In [45]:
var[0:2]

array([ 22, 566])

In [46]:
var[1:3]

array([566,  44])

In [47]:
var[1:-1]

array([566,  44])

In [50]:
arr=np.array([1.,2,3,4,5,61,8])
arr

array([ 1.,  2.,  3.,  4.,  5., 61.,  8.])

In [51]:
arr.dtype

dtype('float64')

In [52]:
arr.size

7

## create a numpy array with size 5 and datatype of string

In [59]:
aa = np.array(['a','sjf','d','f','g'])
aa.size

5

In [60]:
aa.dtype

dtype('<U3')

## create a numpy array with size 5 and datatype of string

In [61]:
a1=np.array([1,23.4,3,8,9])
a1.dtype

dtype('float64')

In [ ]:
# create 2 dimension array
# 4 arrays in the external arrays
# it should have 2 elements each

In [64]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
a.ndim

2

In [65]:
x=np.array([2,3,5,6])
x

array([2, 3, 5, 6])

In [66]:
np.sqrt(x)

array([1.41421356, 1.73205081, 2.23606798, 2.44948974])

In [67]:
np.log(x)

array([0.69314718, 1.09861229, 1.60943791, 1.79175947])

In [74]:
np.shape(a)

(4, 2)

In [75]:
# Transpose
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [77]:
a.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [78]:
# Floor and Ceil

arr2=np.array([2.3,56.7])
arr2

array([ 2.3, 56.7])

In [79]:
np.ceil(arr2) # we will get bthe next integer

array([ 3., 57.])

In [80]:
np.round(arr2)

array([ 2., 57.])

In [83]:
# stacking

import numpy as np
ar=np.arange(10).reshape(2,5)
aar=np.arange(20).reshape(4,5)

ar

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
np.vstack((ar,aar)) # the number of columns should be equale for both array .  vstack (vertical stack)
  # the number of row should be equale for both array.  hstack (harizantal stack)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
# numpy split
ab = np.arange(100).reshape(10,10)
ab

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
np.vsplit(ab,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [89]:
np.hsplit(ab,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]